export const CATEGORY_LIST = 'CATEGORY_LIST';
export const SET_PHRASES = 'SET_PHRASES';
export const SET_CATEGORYLIST_ID = 'SET_CATEGORYLIST_ID';
export const CATEGORY_NAME = 'CATEGORY_NAME';
export const LEARNING_SCREEN_DATA = 'LEARNING_SCREEN_DATA';
export const LEARNING_SCREEN_LEARNT_PRASES = 'LEARNING_SCREEN_LEARNT_PRASES';
export const SEEN_PHRASES = 'SEEN_PRASES';
export const LEARNT_PHRASES = 'LEARNT_PHRASES';
